name = "Blue Lotus - Beyond"
author = "tazta2ra"
version = "b0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8ce08aae4a373e91059844cc5234d79164cc869254b786b60091368253fa2fa"

[versions]
minecraft = "1.20.1"
quilt = "0.19.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "modpack/datapacks"
